{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "935b7c04",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/lilly/miniconda3/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import torchvision\n",
    "from torch.utils.data import Dataset\n",
    "import torchvision.transforms.functional as fn\n",
    "import torchvision.transforms as T\n",
    "import matplotlib.pyplot as plt\n",
    "from utilities import createAnnotation\n",
    "from model_loader import get_new_model\n",
    "import pandas as pd\n",
    "from IPython.display import display\n",
    "from PIL import Image \n",
    "import random\n",
    "import numpy as np\n",
    "import tqdm as notebook_tqdm\n",
    "import gradio as gr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "dc5758fd",
   "metadata": {},
   "outputs": [],
   "source": [
    "emails = {'er':1}\n",
    "userId = 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "8fc1f293",
   "metadata": {},
   "outputs": [],
   "source": [
    "def displayEval(userId):\n",
    "    loadDataFromModel()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "3ac1babe",
   "metadata": {},
   "outputs": [],
   "source": [
    "def loadDataFromModel():\n",
    "    model = get_new_model(\"convnext_tiny\", not_original=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "54467e96",
   "metadata": {},
   "outputs": [],
   "source": [
    "def generateEval():\n",
    "    with gr.Blocks() as demo:\n",
    "        labels = generateLabels()\n",
    "        image = generateImage()\n",
    "        iidBtn = gr.Button(\"IID\")\n",
    "        oodBtn = gr.Button(\"OOD\")\n",
    "        abstinentBtn = gr.Button(\"abstinent\")\n",
    "        iidBtn.click(fn=selectIid, inputs=None, outputs=None, api_name=\"IID\")\n",
    "        oodBtn.click(fn=selectOod, inputs=None, outputs=None, api_name=\"OOD\")\n",
    "        abstinentBtn.click(fn=selectAbstinent, inputs=None, outputs=None, api_name=\"abstinent\")\n",
    "        \n",
    "        \n",
    "    # Bild\n",
    "    # Labels\n",
    "    # Buttons inklusive eventlistener zu buttons = update json"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b5ee9bc0",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "expected an indented block after function definition on line 1 (4192718073.py, line 3)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  Cell \u001b[0;32mIn[6], line 3\u001b[0;36m\u001b[0m\n\u001b[0;31m    def selectOod():\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mIndentationError\u001b[0m\u001b[0;31m:\u001b[0m expected an indented block after function definition on line 1\n"
     ]
    }
   ],
   "source": [
    "def selectIid():\n",
    "    \n",
    "def selectOod():\n",
    "    \n",
    "def selectAbstinent():"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "8f13ddb3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running on local URL:  http://127.0.0.1:7955\n",
      "Running on public URL: https://f4505d1ad2e638c520.gradio.live\n",
      "\n",
      "This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"https://f4505d1ad2e638c520.gradio.live\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1420745960.py\", line 2, in generateId\n",
      "    userId = userId + 1\n",
      "UnboundLocalError: local variable 'userId' referenced before assignment\n"
     ]
    }
   ],
   "source": [
    "def generateId():\n",
    "    userId = userId + 1\n",
    "    return userId\n",
    "        \n",
    "\n",
    "def checkMail(mail):\n",
    "    for email, uId in emails.items():\n",
    "        if email == mail:\n",
    "            with gr.Blocks() as demo:\n",
    "                gr.Markdown('''\n",
    "                You already have an userId!\n",
    "                ''')\n",
    "                backToSignInBtn = gr.Button(\"Back to sign in\")\n",
    "                backToSignInBtn.click(fn=generateSignIn, inputs=None, outputs=None, api_name=\"Back to sign in\")\n",
    "                \n",
    "            demo.launch(share=True)\n",
    "            \n",
    "    demo = gr.Interface(\n",
    "        fn = generateId,\n",
    "        inputs=None,\n",
    "        outputs = gr.Textbox(type=\"text\"))\n",
    "        \n",
    "    demo.launch(share=True)\n",
    "         \n",
    "checkMail(\"e\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "6ef3c8b3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running on local URL:  http://127.0.0.1:7956\n",
      "Running on public URL: https://eb6e839f0d00dd4739.gradio.live\n",
      "\n",
      "This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"https://eb6e839f0d00dd4739.gradio.live\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'er'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'er'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'er'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'er'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'er'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'e'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'e'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'e'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 7, in handleFirstIn\n",
      "    askAmount(idOrMail)\n",
      "NameError: name 'askAmount' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'er'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'er'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'er'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'er'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 3, in handleFirstIn\n",
      "    int(idOrMail)\n",
      "ValueError: invalid literal for int() with base 10: 'er'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/routes.py\", line 408, in run_predict\n",
      "    output = await app.get_blocks().process_api(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1315, in process_api\n",
      "    result = await self.call_function(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/gradio/blocks.py\", line 1043, in call_function\n",
      "    prediction = await anyio.to_thread.run_sync(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"/home/lilly/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"/tmp/ipykernel_3101/1601787792.py\", line 5, in handleFirstIn\n",
      "    generateId(idOrMail)\n",
      "TypeError: generateId() takes 0 positional arguments but 1 was given\n"
     ]
    }
   ],
   "source": [
    "def handleFirstIn(idOrMail):\n",
    "    try: \n",
    "        int(idOrMail)\n",
    "    except:\n",
    "        generateId(idOrMail)\n",
    "    else: \n",
    "        askAmount(idOrMail) \n",
    "\n",
    "def generateSignIn():\n",
    "    with gr.Blocks() as demo:\n",
    "        idOrMail = gr.Textbox(label=\"Please enter your UserID or, in case you don´t have one yet, please enter your e-mail address:\", placeholder=\"UserID or e-mail\")\n",
    "        signInBtn = gr.Button(\"Sign in\")\n",
    "        signInBtn.click(fn=handleFirstIn, inputs=idOrMail, outputs=None, api_name=\"Sign in\")\n",
    "\n",
    "    demo.launch(share=True)\n",
    "    \n",
    "generateSignIn()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1fe70683",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
